### ISSUE TITLE
Did you mean to open source this?

### ISSUE THREAD

**Issue by jeffwidman** [jdambly/atlas#1]
Do you realize this is now open-source?

1. https://github.com/jdambly/atlas/blob/4241bc02877aa615ddb4ff9b1c5c7970fcbf8301/templates/base.html#L12
2. https://github.com/jdambly/atlas/tree/master/nsproxy

**Comment by jdambly** [comment]
yes, this is getting a re-write and I put it here for easier sharing

**Comment by jdambly** [comment]
yep
